INSERT IGNORE INTO units(name) VALUES
('cup'),
('tsp'),
('thumb'),
('bulb'),
('shot'),
('tbsp'),
('oz'),
('g'),
(''),
('stalk'),
('to taste'),
('pack'),
('small'),
('medium'),
('large');

INSERT IGNORE INTO categories(name) VALUES
('Desserts and Sweets'),
('Soups and Stews'),
('Bread'),
('Salads'),
('Snacks'),
('Dressings and Sauces'),
('Main Dishes');

INSERT IGNORE INTO diets(name) VALUES
('Keto'),
('Atkins'),
('Paleo'),
('Pescatarian'),
('Vegetarian'),
('Vegan'),
('Halal-friendly'),
('Kosher-friendly');

INSERT IGNORE INTO feedback_categories(category) VALUES
('Add Unit'),
('Add Diet'),
('Bug Report'),
('Report Recipe'),
('Delete Recipe'),
('Other');

INSERT IGNORE INTO users(username, password) VALUES
('dev_cad', '$argon2i$v=19$m=65536,t=10,p=1$9sX6+jn9Iw2bfg/X2H/rVA$UfbGHk+VR3AT2emoGuTQw80Qf+K1qmDjGaTsaGWFfxo');

INSERT INTO Ingredients(name) VALUES
('ginger'),
('green onion'),
('shiitake mushrooms'),
('tofu'),
('vegetable broth'),
('rice vinegar'),
('sesame oil'),
('soy sauce'),
('eggs'),
('salt'),
('white pepper'),
('butter'),
('sugar'),
('milk'),
('vanilla extract'),
('flour'),
('cocoa powder'),
('baking powder'),
('chocolate chips'),
('marshmallows'),
('walnuts'),
('pomegranate seeds'),
('dried persimmon slices'),
('dried cranberries'),
('neutral vegetable oil'),
('plant milk'),
('egg yolks'),
('mascarpone'),
('ladyfingers'),
('rum'),
('coffee'),
('heavy whipping cream'),
('espresso'),
('chicken thigh'),
('Korean rice cake'),
('rice wine'),
('ginger powder'),
('black pepper'),
('potato starch'),
('cooking oil'),
('ketchup'),
('gochujang'),
('honey'),
('brown sugar'),
('garlic'),
('Korean fish cake'),
('Korean soup stock'),
('onion'),
('gochugaru'),
('sesame seeds'),
('jajangmyeon noodles'),
('zucchini'),
('potato'),
('button mushrooms'),
('cabbage'),
('pork'),
('Korean black bean paste'),
('lard'),
('chicken stock'),
('cucumber');

INSERT INTO recipe_summaries(name, serving_size, prep_time_min, cook_time_min, calories)  VALUES
('Rocky Road Brownies', 9, 10, 30, NULL),
('Mabon Brownies', 9, 10, 30, 430),
('Tiramisu', 18, 1440 ,20, NULL),
('Not-so-Hot and Sour Soup', 8, 20, 40, NULL),
('Vegan Brownies', 9, 10, 30, 378),
('Espresso Brownies', 9, 10, 30, 410),
('Basic Brownies', 9, 10, 30, 380),
('Korean Style Popcorn Chicken', 3, 40, 25, 758),
('Tteokbokki', 2, 10, 10, 381),
('Jajangmyeon', 6, 20, 30, 522);


INSERT INTO recipe_full(recipe_id, description) VALUES
(4, '1. Press the tofu to remove excess water. \n 2. Heat 1 tsp oil in a soup pot. Toss in sliced ginger and chopped green onion. Pan fry until starting to brown. \n 3. Add vegetable broth and let steep for at least 5 minutes. Remove ginger and green onion. Add in soy sauce and rice vinegar. \n 4. Chop mushrooms and toss in. \n 5. Once mushrooms have noticeable shrunk, chop and toss in tofu. \n 6. Let sit for about 15 minutes. \n 7. Whisk eggs. While stirring the soup, pour the eggs in a steady stream, aiming to create ribbons. \n 8. Add the sesame oil, then salt and pepper to taste.'),
(1, '1. Preheat oven to 350F \n 2. Line baking pan with parchment paper \n 3. mix melted butter and sugar. Then whisk in the milk and vanilla \n 4. Combine flour, cocoa powder, baking powder, and salt in separate bowl \n 5. Mix the dry mixture with the butter and sugar mixture until well combined \n 6. Fold in chocolate chips, marshmallows, and walnuts \n 7. Spread batter in baking pan evenly \n 8. Bake for 25-30 minutes, or until edges look hardened and top looks set \n 9. Let cool before cutting and serving'),
(7, '1. Preheat oven to 350F \n 2. Line baking pan with parchment paper \n 3. mix melted butter and sugar. Then whisk in the milk and vanilla \n 4. Combine flour, cocoa powder, baking powder, and salt in separate bowl \n 5. Mix the dry mixture with the butter and sugar mixture until well combined \n 6. Fold in chocolate chips \n 7. Spread batter in baking pan evenly \n 8. Bake for 25-30 minutes, or until edges look hardened and top looks set \n 9. Let cool before cutting and serving'),
(5, '1. Preheat oven to 350F \n 2. Line baking pan with parchment paper \n 3. mix melted butter and sugar. Then whisk in the milk and vanilla \n 4. Combine flour, cocoa powder, baking powder, and salt in separate bowl \n 5. Mix the dry mixture with the butter and sugar mixture until well combined \n 6. Fold in chocolate chips \n 7. Spread batter in baking pan evenly \n 8. Bake for 25-30 minutes, or until edges look hardened and top looks set \n 9. Let cool before cutting and serving'),
(6, '1. Preheat oven to 350F \n 2. Line baking pan with parchment paper \n 3. mix melted butter and sugar. Then whisk in the milk, Espresso, and vanilla \n 4. Combine flour, cocoa powder, baking powder, and salt in separate bowl \n 5. Mix the dry mixture with the butter and sugar mixture until well combined \n 6. Fold in chocolate chips \n 7. Spread batter in baking pan evenly \n 8. Bake for 25-30 minutes, or until edges look hardened and top looks set \n 9. Let cool before cutting and serving'),
(2, '1. Preheat oven to 350F \n 2. Line baking pan with parchment paper \n 3. mix melted butter and sugar. Then whisk in the milk and vanilla \n 4. Combine flour, cocoa powder, baking powder, and salt in separate bowl \n 5. Mix the dry mixture with the butter and sugar mixture until well combined \n 6. Fold in chocolate chips, cranberries, pomegranate seeds, and persimmon slices. \n 7. Spread batter in baking pan evenly \n 8. Bake for 25-30 minutes, or until edges look hardened and top looks set \n 9. Let cool before cutting and serving'),
(3, '1. Whisk egg yolks and sugar in a double boiler for 15 minutes. Set aside to cool. \n 2. Whip heavy cream. \n 3. Add small amount of rum and mascarpone to cooled egg mixture, and mix until smooth. \n 4. Fold mascarpone mixture into whipped cream. \n 5. Soak ladyfingers in rum and coffee mixture. \n 6. Alternate layers of ladyfingers and cream mixture. \n 7. Top with cocoa powder. \n 8. Let rest in fridge at least 12 hours before serving.'),
(8, '1. Place chicken pieces in a bowl. Add rice wine, ginger powder, salt, and black pepper. Mix well, cover, and marinate in the fridge for 30 mins. \n 2. Coat each chicken piece thoroughly with potato starch. \n 3. Heat cooking oil in a deep saucepan to 175C/347F. Deep fry rice cakes in batches for under 10 seconds until outer layer is crispy. Set aside on paper towels. \n 4. Deep fry battered chicken in batches for 2-3 mins until golden and cooked through. Set aside on paper towels. For extra crunch, double fry the chicken. \n 5. Mix ketchup, gochujang, honey, brown sugar, soy sauce, sesame oil, and minced garlic in a bowl. \n 6. Pour sauce into a heated skillet and bring to boil on medium heat for 1-2 mins, stirring constantly, until slightly thickened. \n 7. Add fried chicken and rice cakes and coat quickly and thoroughly with sauce. Serve immediately.'),
(9, '1. Soak rice cakes in warm water for 10 minutes. \n 2. Mix gochujang, sugar, soy sauce, minced garlic, and gochugaru in a bowl to make the sauce. \n 3. Boil soup stock in a shallow pot over medium high heat. Dissolve the sauce into the stock. \n 4. Once boiling, add rice cakes, fish cakes, and sliced onion. Boil for 3-5 mins until rice cakes are fully cooked. \n 5. Simmer on low heat for a further 2-4 mins to thicken the sauce. \n 6. Add sesame oil, sesame seeds, and chopped green onion. Stir quickly and serve warm.'),
(10, '1. Rinse pork and pat dry. Mix with rice wine, salt, black pepper, and ginger powder. Marinate for 15 mins. \n 2. Cut onion, zucchini, and potato into small cubes. Thin slice mushrooms. Cut cabbage into small pieces. Julienne cut cucumber and set aside. \n 3. Heat wok and add lard. Add black bean paste and stir on medium heat for 3-5 mins. Add brown sugar and stir for 2-3 more mins. Scoop out paste and set aside. \n 4. Add pork to wok and stir until half cooked. Add onion, zucchini, and potato and stir for 3-5 mins. Add mushrooms and cabbage and stir for 2-3 mins. \n 5. Add black bean paste back in and mix. Add chicken stock and rice wine and simmer for 5-7 mins. \n 6. Mix potato starch with water and stir into wok to thicken sauce. \n 7. Boil noodles for 3-5 mins. Rinse in cold water and drain. \n 8. Pour black bean sauce over noodles. Top with cucumber. Serve immediately.');

INSERT INTO recipe_ingredients(recipe_id, ingredient_id, unit_id, amount) VALUES
(4, 'ginger', 3, 1),
(4, 'green onion', 8, 6),
(4, 'shiitake mushrooms', 1, 1),
(4, 'tofu', 10, 1),
(4, 'vegetable broth', 1, 8),
(4, 'rice vinegar', 1, 0.25),
(4, 'sesame oil', 2, 2),
(4, 'soy sauce', 1, 0.25),
(4, 'eggs', 7, '4'),
(4, 'salt', 9, 0),
(4, 'white pepper', 9, 0),
(1, 'butter', 1, 0.5),
(1, 'sugar', 1, 1.5),
(1, 'milk', 1, 0.33),
(1, 'vanilla extract', 2, 3),
(1, 'flour', 1, 1),
(1, 'cocoa powder', 1, 0.75),
(1, 'baking powder', 2, 0.75),
(1, 'salt', 2, 0.25 ),
(1, 'chocolate chips', 1, 1),
(1, 'marshmallows', 1, 0.5),
(1, 'walnuts', 1, 0.5),
(7, 'butter', 1, 0.5),
(7, 'sugar', 1, 1.5),
(7, 'milk', 1, 0.33),
(7, 'vanilla extract', 2, 3),
(7, 'flour', 1, 1),
(7, 'cocoa powder', 1, 0.75),
(7, 'baking powder', 2, 0.75),
(7, 'salt', 2, 0.25),
(7, 'chocolate chips', 1, 1),
(6, 'butter', 1, 0.5),
(6, 'sugar', 1, 1.5),
(6, 'milk', 1, 0.33),
(6, 'vanilla extract', 2, 3),
(6, 'flour', 1, 1.25),
(6, 'cocoa powder', 1, 0.75),
(6, 'baking powder', 2, 0.75),
(6, 'salt', 2, 0.5),
(6, 'chocolate chips', 1, 1),
(6, 'espresso', 5, 4),
(5, 'neutral vegetable oil', 1, 0.5),
(5, 'sugar', 1, 1.5),
(5, 'plant milk', 1, 0.33),
(5, 'vanilla extract', 2, 3),
(5, 'flour', 1, 1),
(5, 'cocoa powder', 1, 0.75),
(5, 'baking powder', 2, 0.75),
(5, 'salt', 2, 0.25),
(5, 'chocolate chips', 1, 1),
(2, 'butter', 1, 0.5),
(2, 'sugar', 1, 1.5),
(2, 'milk', 1, 0.33),
(2, 'vanilla extract', 2, 3),
(2, 'flour', 1, 1),
(2, 'cocoa powder', 1, 0.75),
(2, 'baking powder', 2, 0.75),
(2, 'salt', 2, 0.25),
(2, 'chocolate chips', 1, 1),
(2, 'pomegranate seeds', 1, 0.5),
(2, 'dried persimmon slices', 1, 0.5),
(2, 'dried cranberries', 1, 0.5),
(3, 'egg yolks', 7, '4'),
(3, 'sugar', 1, 0.25),
(3, 'mascarpone', 1, 1),
(3, 'ladyfingers', 10, 2),
(3, 'rum', 6, 4),
(3, 'coffee', 1, 1),
(3, 'heavy whipping cream', 1, 1),
(3, 'cocoa powder', 9, 0),
(8, 'chicken thigh', 7, NULL),
(8, 'Korean rice cake', 7, NULL),
(8, 'rice wine', 6, 1),
(8, 'ginger powder', 2, 2),
(8, 'salt', 2, 0.5),
(8, 'black pepper', 2, 0.25),
(8, 'potato starch', 1, 1),
(8, 'cooking oil', 7, NULL),
(8, 'ketchup', 6, 5),
(8, 'gochujang', 6, 1.5),
(8, 'honey', 6, 2),
(8, 'brown sugar', 6, 2),
(8, 'soy sauce', 6, 1),
(8, 'sesame oil', 2, 2),
(8, 'garlic', 2, 0.5),
(9, 'Korean rice cake', 7, NULL),
(9, 'Korean fish cake', 7, NULL),
(9, 'Korean soup stock', 1, 2),
(9, 'onion', 7, NULL),
(9, 'gochujang', 6, 3),
(9, 'sugar', 6, 1.5),
(9, 'soy sauce', 6, 1),
(9, 'garlic', 2, 1),
(9, 'gochugaru', 2, 1),
(9, 'sesame seeds', 2, 1),
(9, 'sesame oil', 2, 1),
(9, 'green onion', 8, 1),
(10, 'jajangmyeon noodles', 7, NULL),
(10, 'onion', 7, NULL),
(10, 'zucchini', 7, NULL),
(10, 'potato', 7, NULL),
(10, 'button mushrooms', 7, NULL),
(10, 'cabbage', 7, NULL),
(10, 'pork', 7, NULL),
(10, 'rice wine', 6, 5),
(10, 'salt', 9, 0),
(10, 'black pepper', 9, 0),
(10, 'ginger powder', 2, 0.25),
(10, 'Korean black bean paste', 6, 6),
(10, 'lard', 7, NULL),
(10, 'brown sugar', 6, 2),
(10, 'chicken stock', 1, 1),
(10, 'potato starch', 6, 5),
(10, 'cucumber', 7, NULL);

INSERT INTO recipe_categories(recipe_id, category_id) VALUES
(4, 2),
(1, 1),
(3, 1),
(7, 1),
(6, 1),
(5, 1),
(2, 1),
(8, 5),
(9, 5),
(10, 7);

INSERT INTO recipe_diets(recipe_id, diet_id) VALUES
(7, 5),
(6, 5),
(5, 6),
(5, 5),
(3, 5),
(4, 5),
(1, 5),
(2, 5),
(7, 7),
(6, 7),
(5, 7),
(3, 7),
(4, 7),
(1, 7),
(7, 8),
(6, 8),
(5, 8),
(3, 8),
(4, 8),
(1, 8),
(8, 7),
(9, 7);