INSERT INTO Ingredients(name) VALUES
('chicken thigh'),
('Korean rice cake'),
('rice wine'),
('ginger powder'),
('black pepper'),
('potato starch'),
('cooking oil'),
('ketchup'),
('gochujang'),
('honey'),
('brown sugar'),
('garlic'),
('Korean fish cake'),
('Korean soup stock'),
('onion'),
('gochugaru'),
('sesame seeds'),
('jajangmyeon noodles'),
('zucchini'),
('potato'),
('button mushrooms'),
('cabbage'),
('pork'),
('Korean black bean paste'),
('lard'),
('chicken stock'),
('cucumber');